In [1]:
import pandas as pd
import numpy as np
import torch

# Loading the data

First, let's examine what the data looks like.

(Note: This repo does not contain the full data. To get the full data, go to the [Kaggle competition page](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge) and download the data for yourself.

In [2]:
pd.read_csv("data/train.csv").head(2)

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0

In [3]:
pd.read_csv("data/valid.csv").head(3)

id                                       comment_text  toxic  \
0  000eefc67a2c930f  Radial symmetry \n\nSeveral now extinct lineag...      0   
1  000f35deef84dc4a  There's no need to apologize. A Wikipedia arti...      0   
2  000ffab30195c5e1  Yes, because the mother of the child in the ca...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0

Apparently we have to predict 6 labels

In [4]:
pd.read_csv("data/test.csv").head(2)

id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...

### Declaring Fields

The Field class determines how the data is preprocessed and converted into a numeric format

In [5]:
from torchtext.data import Field

We want comment_text field to be converted to lowercase, tokenized on whitespace, and preprocessed. So we tell that to the Field

In [6]:
tokenize = lambda x: x.split()
TEXT = Field(sequential=True, tokenize=tokenize, lower=True)

That was simple. The preprocessing of the labels is even easier, since they are already converted into a binary encoding.
All we need to do is to tell the Field class that the labels are already processed. We do this by passing the use_vocab=False keyword to the constructor

In [7]:
LABEL = Field(sequential=False, use_vocab=False)

### Creating the Dataset

We'll use the TabularDataset class to read our data, since it is in csv format (TabularDataset handles csv, tsv, and json files as of now)

In [8]:
from torchtext.data import TabularDataset

For the train and validation data, we need to process the labels. The fields we pass in must be in the same order as the columns. For fields we don't use, we pass in a tuple where the second element is None

In [9]:
%%time
tv_datafields = [("id", None), # we won't be needing the id, so we pass in None as the field
                 ("comment_text", TEXT), ("toxic", LABEL),
                 ("severe_toxic", LABEL), ("threat", LABEL),
                 ("obscene", LABEL), ("insult", LABEL),
                 ("identity_hate", LABEL)]

trn, vld = TabularDataset.splits(
        path="data", # the root directory where the data lies
        train='train.csv', validation="valid.csv",
        format='csv',
        skip_header=True, # if your csv header has a header, make sure to pass this to ensure it doesn't get proceesed as data!
        fields=tv_datafields)

CPU times: user 4.27 ms, sys: 39 µs, total: 4.31 ms
Wall time: 3.68 ms


In [60]:
trn[0].toxic

'0'

For the test data, we don't have any labels

In [10]:
%%time
tst_datafields = [("id", None), # we won't be needing the id, so we pass in None as the field
                 ("comment_text", TEXT)
]

tst = TabularDataset(
        path="data/test.csv", # the file path
        format='csv',
        skip_header=True, # if your csv header has a header, make sure to pass this to ensure it doesn't get proceesed as data!
        fields=tst_datafields)

CPU times: user 3.54 ms, sys: 0 ns, total: 3.54 ms
Wall time: 2.95 ms


For the TEXT field to convert words into integers, it needs to be told what the entire vocabulary is. To do this, we run TEXT.build_vocab, passing in the dataset to build the vocabulary on.

In [11]:
%%time
TEXT.build_vocab(trn)

CPU times: user 2.28 ms, sys: 0 ns, total: 2.28 ms
Wall time: 2.29 ms


Let's take a look at what the vocab looks like.

The vocab.freqs is a collections.Counter object, so we can take a look at the most frequent words.

In [22]:
TEXT.vocab.stoi

defaultdict(<function torchtext.vocab._default_unk_index()>,
            {'<unk>': 0,
             '<pad>': 1,
             'the': 2,
             'to': 3,
             'you': 4,
             'of': 5,
             'a': 6,
             'and': 7,
             'is': 8,
             'that': 9,
             'i': 10,
             'if': 11,
             'be': 12,
             'in': 13,
             'this': 14,
             '"': 15,
             'have': 16,
             'it': 17,
             'on': 18,
             'at': 19,
             'for': 20,
             'use': 21,
             'are': 22,
             'not': 23,
             'any': 24,
             'as': 25,
             'can': 26,
             'he': 27,
             'copyright': 28,
             'fair': 29,
             "i'm": 30,
             'or': 31,
             'page': 32,
             'please': 33,
             'then': 34,
             'with': 35,
             'about': 36,
             'his': 37,
             'me': 38,
          

In [18]:
TEXT.vocab.freqs

Counter({'explanation': 4,
         'why': 4,
         'the': 78,
         'edits': 4,
         'made': 2,
         'under': 6,
         'my': 6,
         'username': 1,
         'hardcore': 1,
         'metallica': 1,
         'fan': 1,
         'were': 1,
         'reverted?': 1,
         'they': 5,
         "weren't": 1,
         'vandalisms,': 1,
         'just': 2,
         'closure': 1,
         'on': 16,
         'some': 4,
         'gas': 1,
         'after': 5,
         'i': 20,
         'voted': 1,
         'at': 14,
         'new': 2,
         'york': 1,
         'dolls': 1,
         'fac.': 1,
         'and': 26,
         'please': 9,
         "don't": 5,
         'remove': 1,
         'template': 1,
         'from': 6,
         'talk': 4,
         'page': 9,
         'since': 2,
         "i'm": 9,
         'retired': 1,
         'now.89.205.38.27': 1,
         "d'aww!": 1,
         'he': 10,
         'matches': 1,
         'this': 17,
         'background': 1,
         'co

In [17]:
len(TEXT.vocab.freqs)

782

In [ ]:
#the two difference between 782 and 784 may be from '<unk>': 0, '<pad>': 1,

In [16]:
len(TEXT.vocab)

784

It is also instructive to take a look inside the Dataset. Datasets can be indexed like normal lists, so we'll look at the first element.

In [23]:
len(trn)

25

Each element of the dataset is an Example object that bundles the attributes of a single data point together.

In [24]:
trn[0].__dict__.keys()

dict_keys(['comment_text', 'toxic', 'severe_toxic', 'threat', 'obscene', 'insult', 'identity_hate'])

In [35]:
trn.__dict__['examples']

In [36]:
trn[0].__dict__.values()

dict_values([['explanation', 'why', 'the', 'edits', 'made', 'under', 'my', 'username', 'hardcore', 'metallica', 'fan', 'were', 'reverted?', 'they', "weren't", 'vandalisms,', 'just', 'closure', 'on', 'some', 'gas', 'after', 'i', 'voted', 'at', 'new', 'york', 'dolls', 'fac.', 'and', 'please', "don't", 'remove', 'the', 'template', 'from', 'the', 'talk', 'page', 'since', "i'm", 'retired', 'now.89.205.38.27'], '0', '0', '0', '0', '0', '0'])

We see that the comment text is already tokenized for us.

In [37]:
trn[0].comment_text[:3]

['explanation', 'why', 'the']

Looking good. Now, let's build the Iterator which will allow us to load the data into our model.

### Creating the Iterator

In [39]:
from torchtext.data import Iterator, BucketIterator

During training, we'll be using a special kind of Iterator, called the **BucketIterator**.

When we pass data into a neural network, we want the data to be padded to be the same length so that we can process them in batch:

e.g.
\[ 
\[3, 15, 2, 7\],
\[4, 1\], 
\[5, 5, 6, 8, 1\] 
\] -> \[ 
\[3, 15, 2, 7, **0**\],
\[4, 1, **0**, **0**, **0**\], 
\[5, 5, 6, 8, 1\] 
\] 

If the sequences differ greatly in length, the padding will consume a lot of wasteful memory and time.

The BucketIterator groups sequences of similar lengths together for each batch to minimize padding. Handy, right?

In [143]:
train_iter, val_iter = BucketIterator.splits(
        (trn, vld), # we pass in the datasets we want the iterator to draw data from
#         batch_sizes=(64, 64),
        batch_sizes=(23,23),
#         device=torch.device, # if you want to use the GPU, specify the GPU number here
        sort_key=lambda x: len(x.comment_text), # the BucketIterator needs to be told what function it should use to group the data.
        sort_within_batch=False,
        repeat=False # we pass repeat=False because we want to wrap this Iterator layer.
)

Let's take a look at what the output of the BucketIterator looks like

In [94]:
batch = next(train_iter.__iter__()); batch


[torchtext.data.batch.Batch of size 23]
	[.comment_text]:[torch.LongTensor of size 228x23]
	[.toxic]:[torch.LongTensor of size 23]
	[.severe_toxic]:[torch.LongTensor of size 23]
	[.threat]:[torch.LongTensor of size 23]
	[.obscene]:[torch.LongTensor of size 23]
	[.insult]:[torch.LongTensor of size 23]
	[.identity_hate]:[torch.LongTensor of size 23]

The batch has all the fields we passed to the Dataset as attributes. The batch data can be accessed through the attribute with the same name.

In [95]:
batch.__dict__.keys()

dict_keys(['batch_size', 'dataset', 'fields', 'input_fields', 'target_fields', 'comment_text', 'toxic', 'severe_toxic', 'threat', 'obscene', 'insult', 'identity_hate'])

For the test set, we don't want the data to be shuffled. This is why we'll be using a standard Iterator.

In [145]:
test_iter = Iterator(tst, batch_size=20,sort=False, sort_within_batch=False, repeat=False)

In [97]:
batch.batch_size

23

In [98]:
len(batch.dataset)

25

### Wrapping the Iterator

Currently, the iterator returns a custom datatype called torchtext.data.Batch. This makes code reuse difficult (since each time the column names change, we need to modify the code), and makes torchtext hard to use with other libraries for some use cases (like torchsample and fastai). 

I hope this will be dealt with in the future (I'm considering filing a PR if I can decide what the API should look like), but in the meantime, we'll hack on a simple wrapper to make the batches easy to use. 

Concretely, we'll convert the batch to a tuple in the form (x, y) where x is the independent variable (the input to the model) and y is the dependent variable (the supervision data).

In [128]:
for batch in train_iter:
    x = getattr(batch, self.x_var) # we assume only one input in this wrapper

    if self.y_vars is not None: # we will concatenate y into a single tensor
        y = torch.cat([getattr(batch, feat).unsqueeze(1) for feat in self.y_vars], dim=1).float()
    else:
        y = torch.zeros((1))

    yield (x, y)

SyntaxError: 'yield' outside function (<ipython-input-128-22c96d9e1421>, line 9)

In [124]:
a=next(train_iter.__iter__())
a.comment_text

tensor([[ 15, 453,  55,  ...,  15, 660, 280],
        [360, 523, 531,  ...,  29,  11,  18],
        [ 45,  30,   3,  ...,  21,   2,  14],
        ...,
        [  1,   1,   1,  ...,  84,   1,   1],
        [  1,   1,   1,  ..., 118,   1,   1],
        [  1,   1,   1,  ...,  15,   1,   1]])

In [126]:
a.comment_text.shape

torch.Size([494, 23])

In [127]:
a


[torchtext.data.batch.Batch of size 23]
	[.comment_text]:[torch.LongTensor of size 494x23]
	[.toxic]:[torch.LongTensor of size 23]
	[.severe_toxic]:[torch.LongTensor of size 23]
	[.threat]:[torch.LongTensor of size 23]
	[.obscene]:[torch.LongTensor of size 23]
	[.insult]:[torch.LongTensor of size 23]
	[.identity_hate]:[torch.LongTensor of size 23]

In [108]:
getattr

<function getattr>

In [146]:
class BatchWrapper:
    def __init__(self, dl, x_var, y_vars):
        self.dl, self.x_var, self.y_vars = dl, x_var, y_vars # we pass in the list of attributes for x and y
    
    def __iter__(self):
        for batch in self.dl:
            x = getattr(batch, self.x_var) # we assume only one input in this wrapper
            
            if self.y_vars is not None: # we will concatenate y into a single tensor
                y = torch.cat([getattr(batch, feat).unsqueeze(1) for feat in self.y_vars], dim=1).float()
            else:
                y = torch.zeros((1))

            yield (x, y)
    
    def __len__(self):
        return len(self.dl)

We'll use this to wrap the BucketIterator

In [147]:
train_dl = BatchWrapper(train_iter, "comment_text", ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"])
valid_dl = BatchWrapper(val_iter, "comment_text", ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"])
test_dl = BatchWrapper(test_iter, "comment_text", None)

In [117]:
a=next(train_dl.__iter__())[0]
next(train_dl.__iter__())

(tensor([[ 15, 606,  15,  ...,  44, 375, 354],
         [ 46, 693, 601,  ..., 739,  27,  63],
         [ 10, 584, 242,  ...,   3, 526,   4],
         ...,
         [  1,   1,   1,  ...,   1,   1,   1],
         [  1,   1,   1,  ...,   1,   1,   1],
         [  1,   1,   1,  ...,   1,   1,   1]]),
 tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
  

In [150]:
a.size()

torch.Size([113, 5])

Now we're ready to start training a model!

In [133]:
next(train_dl.__iter__())[1]

tensor([[0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [110]:
next(train_dl.__iter__())[2]

IndexError: tuple index out of range

# Training a Text Classifier

We'll use a simple LSTM as a baseline example.

In [148]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable

In [149]:
class SimpleBiLSTMBaseline(nn.Module):
    def __init__(self, hidden_dim, emb_dim=300,
                 spatial_dropout=0.05, recurrent_dropout=0.1, num_linear=1):
        super().__init__() # don't forget to call this!
        self.embedding = nn.Embedding(len(TEXT.vocab), emb_dim)
        self.encoder = nn.LSTM(emb_dim, hidden_dim, num_layers=1, dropout=recurrent_dropout)
        self.linear_layers = []
        for _ in range(num_linear - 1):
            self.linear_layers.append(nn.Linear(hidden_dim, hidden_dim))
        self.linear_layers = nn.ModuleList(self.linear_layers)
        self.predictor = nn.Linear(hidden_dim, 6)
    
    def forward(self, seq):
        hdn, _ = self.encoder(self.embedding(seq))
        feature = hdn[-1, :, :]
        for layer in self.linear_layers:
            feature = layer(feature)
        preds = self.predictor(feature)
        return preds

In [150]:
em_sz = 100
nh = 500
nl = 3
model = SimpleBiLSTMBaseline(nh, emb_dim=em_sz); model

SimpleBiLSTMBaseline(
  (embedding): Embedding(784, 100)
  (encoder): LSTM(100, 500, dropout=0.1)
  (linear_layers): ModuleList()
  (predictor): Linear(in_features=500, out_features=6, bias=True)
)

If you're using a GPU, remember to call model.cuda() to move your model to the GPU.

In [27]:
# model.cuda()

In [132]:
for x, y in tqdm.tqdm(train_dl):
    print(x)
    print(x.shape)
    print(y)
    print(y.shape)

100%|██████████| 2/2 [00:00<00:00, 266.47it/s]

tensor([[ 63, 315, 453,  ..., 280, 334,  44],
        [  4,  12, 523,  ...,  18,  55, 739],
        [664,   6,  30,  ...,  14, 520,   3],
        ...,
        [  1,   1,   1,  ...,   1,   1,   1],
        [  1,   1,   1,  ...,   1,   1,   1],
        [  1,   1,   1,  ...,   1,   1,   1]])
torch.Size([494, 23])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        

### The training loop

In [130]:
import tqdm

In [155]:
opt = optim.Adam(model.parameters(), lr=1e-2)
loss_func = nn.BCEWithLogitsLoss()

In [156]:
epochs = 2

In [158]:
%%time
for epoch in range(1, epochs + 1):
    running_loss = 0.0
    running_corrects = 0
    model.train() # turn on training mode
    for x, y in tqdm.tqdm(train_dl): # thanks to our wrapper, we can intuitively iterate over our data!
        opt.zero_grad()

        preds = model(x)
        loss = loss_func(preds, y)
        loss.backward()
        opt.step()
        
        running_loss += loss.item() * x.size(0)
        
    epoch_loss = running_loss / len(trn)
    
    # calculate the validation loss for this epoch
    val_loss = 0.0
    model.eval() # turn on evaluation mode
    for x, y in valid_dl:
        preds = model(x)
        loss = loss_func(preds, y)
        val_loss += loss.data.item() * x.size(0)

    val_loss /= len(vld)
    print('Epoch: {}, Training Loss: {:.4f}, Validation Loss: {:.4f}'.format(epoch, epoch_loss, val_loss))


  0%|          | 0/2 [00:00<?, ?it/s]

Epoch: 1, Training Loss: 6.9697, Validation Loss: 2.0425



100%|██████████| 2/2 [00:08<00:00,  5.64s/it]

Epoch: 2, Training Loss: 16.9768, Validation Loss: 1.7631
CPU times: user 56.4 s, sys: 268 ms, total: 56.6 s
Wall time: 31.3 s


# Writing Predictions

Finally, we output the data in the format required by the competition

In [151]:
test_dl

In [152]:
test_preds = []
for x, y in tqdm.tqdm(test_dl):
    preds = model(x)
    # if you're data is on the GPU, you need to move the data back to the cpu
    # preds = preds.data.cpu().numpy()
    preds = preds.data.numpy()
    # the actual outputs of the model are logits, so we need to pass these values to the sigmoid function
    preds = 1 / (1 + np.exp(-preds))
    test_preds.append(preds)
    print(preds)
    print(preds.shape)
test_preds = np.hstack(test_preds)
print(test_preds)
print(test_preds.shape)

100%|██████████| 2/2 [00:00<00:00,  4.13it/s]

[[0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.5030732  0.5207203  0.475422   0.5145852  0.48815513 0.49939278]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698 0.4842676  0.47546154 0.52316993]
 [0.49953315 0.524947   0.49375698

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [153]:
df = pd.read_csv("data/test.csv")
for i, col in enumerate(["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]):
    df[col] = test_preds[:, i]

# if you want to write the submission file to disk, uncomment and run the below code
# df.drop("comment_text", axis=1).to_csv("submission.csv", index=False)

TypeError: list indices must be integers or slices, not tuple

In [162]:
df.head(3)

id                                       comment_text  \
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...   
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...   
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...   

    toxic  severe_toxic   obscene    threat   insult  identity_hate  
0  0.1479      0.015002  0.000021  0.013003  0.01686       0.000025  
1  0.1479      0.015002  0.000021  0.013003  0.01686       0.000025  
2  0.1479      0.015002  0.000021  0.013003  0.01686       0.000025